SELECT
  *
FROM
  "DB_CREDIT"."PUBLIC"."BUREAU"
LIMIT
  10;



  WITH bureau AS (

    SELECT
        br.SK_ID_CURR,
        br.CREDIT_ACTIVE,
        br.CREDIT_CURRENCY,
        br.DAYS_CREDIT,
        br.DAYS_CREDIT_ENDDATE,
        br.AMT_CREDIT_MAX_OVERDUE,
        br.CREDIT_TYPE,
        br.DAYS_CREDIT_UPDATE,
        br.AMT_ANNUITY

    FROM 
      "DB_CREDIT"."PUBLIC"."BUREAU" AS br
        
  )
  SELECT * FROM bureau

  create warehouse DEFAULT_WF;


  -- Criação tabela dimensão de bureau 
  CREATE OR REPLACE TABLE DB_CREDIT.PUBLIC.DIM_BUREAU (

    SK_ID_CURR INT PRIMARY KEY,
    CREDIT_ACTIVE STRING,
    CREDIT_CURRENCY STRING,
    DAYS_CREDIT INT,
    DAYS_CREDIT_ENDDATE STRING,
    CREDIT_TYPE STRING,
    DAYS_CREDIT_UPDATE STRING,
    AMT_ANNUITY STRING
  )


  -- Inserir os dados  na tabela dimensão

  INSERT INTO DB_CREDIT.PUBLIC.DIM_BUREAU
(
    SK_ID_CURR,
    CREDIT_ACTIVE,
    CREDIT_CURRENCY,
    DAYS_CREDIT,
    DAYS_CREDIT_ENDDATE,
    CREDIT_TYPE,
    DAYS_CREDIT_UPDATE,
    AMT_ANNUITY
)
SELECT
    SK_ID_CURR,
    CREDIT_ACTIVE,
    CREDIT_CURRENCY,
    DAYS_CREDIT,
    DAYS_CREDIT_ENDDATE,
    CREDIT_TYPE,
    DAYS_CREDIT_UPDATE,
    AMT_ANNUITY
FROM 
    "DB_CREDIT"."PUBLIC"."BUREAU" AS br;


    SELECT * FROM  DB_CREDIT.PUBLIC.DIM_BUREAU





-- Criaçaõ da tabela fato

CREATE OR REPLACE TABLE DB_CREDIT.PUBLIC.FAT_CREDIT (
    ID_TRANSACAO INT AUTOINCREMENT,
    SK_ID_CURR INT,  -- Chave estrangeira para a tabela de dimensão
    DATA_TRANSACAO DATE,
    VALOR_TRANSACAO FLOAT,
    CONSTRAINT fk_cliente FOREIGN KEY (SK_ID_CURR) REFERENCES DB_CREDIT.PUBLIC.DIM_APLICATION_PERFIL(SK_ID_CURR)
);



INSERT INTO DB_CREDIT.PUBLIC.FAT_CREDIT (SK_ID_CURR, DATA_TRANSACAO, VALOR_TRANSACAO)
SELECT 
    a.SK_ID_CURR,
    CURRENT_DATE() AS DATA_TRANSACAO,  
    SUM(a.QUANTIDADE_IMPRESTIMO) AS SOMAS_IMPRESTIMO  
FROM 
    "DB_CREDIT"."PUBLIC"."DIM_BUREAU" AS b
JOIN 
    "DB_CREDIT"."PUBLIC"."DIM_APLICATION_PERFIL" AS a ON b.SK_ID_CURR = a.SK_ID_CURR
GROUP BY a.SK_ID_CURR;


SELECT * FROM DB_CREDIT.PUBLIC.FAT_CREDIT


  